# Generated by Django 5.2.7 on 2025-10-29 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingUnitScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hu_code', models.CharField(max_length=100)),
                ('workstation_id', models.CharField(max_length=50)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending QC', max_length=50)),
                ('picker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
