# Generated by Django 5.2.7 on 2025-10-30 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('custom_auth', '0003_workstation_area_workstation_created_at_and_more'),
        ('qc_scan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hu_code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ready_for_packing', 'Ready for Packing'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('done', 'Done'), ('exception', 'Exception')], default='ready_for_packing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_packer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hus_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hus_assigned', to='custom_auth.workstation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handling_units', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='HandlingUnitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(blank=True, null=True)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, default='', max_length=128)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('hu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='qc_scan.handlingunit')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hu_id', 'line_no', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='HandlingUnitScan',
        ),
        migrations.AddIndex(
            model_name='handlingunititem',
            index=models.Index(fields=['sku'], name='idx_qc_item_sku'),
        ),
        migrations.AddIndex(
            model_name='handlingunititem',
            index=models.Index(fields=['barcode'], name='idx_qc_item_barcode'),
        ),
        migrations.AddConstraint(
            model_name='handlingunititem',
            constraint=models.UniqueConstraint(condition=models.Q(('hu__isnull', False), ('line_no__isnull', False)), fields=('hu', 'line_no'), name='uq_qc_item_hu_line'),
        ),
    ]
