# Generated by Django 5.2.7 on 2025-11-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_scan', '0002_handlingunit_handlingunititem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunititem',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='handlingunititem',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handlingunititem',
            name='length_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handlingunititem',
            name='weight_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handlingunititem',
            name='width_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
