# Generated by Django 5.2.7 on 2025-10-30 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_workstation_workstationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workstation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='workstationsession',
            name='current_client_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workstationsession',
            name='current_hu_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workstationsession',
            name='current_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workstationsession',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
